// Generates src/materials/ggx_energy.h: directional albedo E(mu, roughness) of
// the single-scattering GGX lobe with F = 1, and its cosine-weighted average.
#include <cstdio>
#include <cmath>
#include <random>
#include <algorithm>

static const int N = 32;
static std::mt19937 rng(12345);
static double rnd(){ return std::uniform_real_distribution<double>(0,1)(rng); }

static double G1(double ndotv,double a){
	double a2=a*a;
	return 2.0*ndotv/(ndotv+std::sqrt(a2+(1.0-a2)*ndotv*ndotv));
}
static double G2(double ndotv,double ndotl,double a){
	double a2=a*a;
	double gv=ndotl*std::sqrt(a2+(1.0-a2)*ndotv*ndotv);
	double gl=ndotv*std::sqrt(a2+(1.0-a2)*ndotl*ndotl);
	return 2.0*ndotv*ndotl/(gv+gl+1e-7);
}
// Mirrors ggx::sample_vndf in materials/material.h.
static void sample_vndf(double vx,double vy,double vz,double a,
						 double&hx,double&hy,double&hz){
	double vhx=a*vx, vhy=a*vy, vhz=vz;
	double il=1.0/std::sqrt(vhx*vhx+vhy*vhy+vhz*vhz);
	vhx*=il; vhy*=il; vhz*=il;
	double lensq=vhx*vhx+vhy*vhy;
	double t1x,t1y,t1z;
	if(lensq>0){ double s=1.0/std::sqrt(lensq); t1x=-vhy*s; t1y=vhx*s; t1z=0; }
	else { t1x=1; t1y=0; t1z=0; }
	double t2x=vhy*t1z-vhz*t1y, t2y=vhz*t1x-vhx*t1z, t2z=vhx*t1y-vhy*t1x;
	double r=std::sqrt(rnd()), phi=2.0*M_PI*rnd();
	double t=r*std::cos(phi), s2=r*std::sin(phi);
	double bz=std::sqrt(std::max(0.0,1.0-t*t-s2*s2));
	double nhx=t*t1x+s2*t2x+bz*vhx;
	double nhy=t*t1y+s2*t2y+bz*vhy;
	double nhz=t*t1z+s2*t2z+bz*vhz;
	hx=a*nhx; hy=a*nhy; hz=std::max(0.0,nhz);
	double hl=1.0/std::sqrt(hx*hx+hy*hy+hz*hz);
	hx*=hl; hy*=hl; hz*=hl;
}
// VNDF-sampled estimator of the white-Fresnel directional albedo is G2/G1.
static double E_of(double mu,double rough,int NS=200000){
	double a=rough*rough;
	if(a<1e-5) return 1.0;
	mu=std::max(mu,1e-3);
	double vx=std::sqrt(std::max(0.0,1.0-mu*mu)), vy=0, vz=mu;
	double sum=0;
	for(int i=0;i<NS;++i){
		double hx,hy,hz; sample_vndf(vx,vy,vz,a,hx,hy,hz);
		double vdoth=vx*hx+vy*hy+vz*hz;
		double lz=2.0*vdoth*hz-vz;
		if(lz<=0) continue;
		sum+=G2(vz,lz,a)/std::max(G1(vz,a),1e-9);
	}
	return sum/NS;
}
int main(){
	static double E[N][N];
	for(int j=0;j<N;++j){
		double r=(double)j/(N-1);
		for(int i=0;i<N;++i) E[j][i]=E_of((double)i/(N-1), r);
	}
	std::printf("#pragma once\n\n");
	std::printf("// Generated by tools/gen_ggx_energy.cpp -- do not edit.\n");
	std::printf("// E[roughness][mu]: directional albedo of the single-scattering GGX\n");
	std::printf("// lobe with F = 1. Used for Kulla-Conty energy compensation.\n\n");
	std::printf("static const int GGX_E_N = %d;\n\n", N);
	std::printf("// Raw data only: ggx_energy.h instantiates host and device copies.\n");
	std::printf("#define GGX_E_DATA {");
	for(int j=0;j<N;++j){
		std::printf("{");
		for(int i=0;i<N;++i) std::printf("%.6ff%s", E[j][i], i+1<N?",":"");
		std::printf("}%s\n", j+1<N?",":"");
	}
	std::printf("}\n\n");
	std::printf("#define GGX_E_AVG_DATA {");
	for(int j=0;j<N;++j){
		// E_avg = 2 * integral_0^1 E(mu) mu dmu, fine quadrature.
		double r=(double)j/(N-1), acc=0; int Q=512;
		for(int q=0;q<Q;++q){ double mu=(q+0.5)/Q; acc+=E_of(mu,r,20000)*mu; }
		std::printf("%.6ff%s", 2.0*acc/Q, j+1<N?",":"");
		if((j+1)%8==0) std::printf("\n");
	}
	std::printf("}\n");
	return 0;
}
